# Generated by Django 5.0.7 on 2024-08-03 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olcha', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
    ]
