# Generated by Django 5.0.7 on 2024-08-11 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olcha', '0004_alter_groupmodel_slug_alter_groupmodel_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attribute',
            new_name='AttributeModel',
        ),
        migrations.AlterModelOptions(
            name='groupmodel',
            options={'verbose_name': 'Group', 'verbose_name_plural': 'Groups'},
        ),
        migrations.AlterModelOptions(
            name='imagemodel',
            options={'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
        migrations.AlterModelOptions(
            name='productmodel',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='file',
            field=models.FileField(null=True, upload_to='comments/'),
        ),
    ]
