# Generated by Django 5.0.7 on 2024-08-13 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olcha', '0005_rename_attribute_attributemodel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attributemodel',
            options={'verbose_name': 'Attribute', 'verbose_name_plural': 'Attributes'},
        ),
    ]
